### ISSUE TITLE
Inbox / Gmail replys are not parsed properly in local language

### ISSUE THREAD

**Issue by marbergq** [kvannotten/mailstrip#1]
When parsing emails from google Inbox / gmail, the reply is not parsed properly, consider this example: 
(in swedish)

shysst! Vad är du beredd att betala då ?

tors 6 dec. 2018 kl 13:30 skrev Martin Bergqvist <\n7prvvpbgytcgg@example.com>:

> Nytt meddelande
> <#m_6703246277760107873_>
> Nytt meddelande
>
> Du har fått ett nytt meddelande
> Test

is getting parsed as : 
shysst! Vad är du beredd att betala då ?\n\ntors 6 dec. 2018 kl 13:30 skrev Martin Bergqvist <\\n7prvvpbgytcgg@example.com>:

**Comment by kvannotten** [comment]
Closed by #2
