### ISSUE TITLE
Microsoft Outlook headers not being detected in replies

### ISSUE THREAD

**Issue by sazzle2611** [kvannotten/mailstrip#5]
This package is working great for us so thank you but there does seem to be an issue with detecting headers in outlook emails.

```
Outlook message reply test

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550123> for Windows 10

From: Support<mailto:support@test.com>
Sent: 10 July 2020 09:46
Subject: Support - test ticket no. 3


Alan Smith has created the support ticket test ticket no. 3<https://test.co.uk/support/edit/345>.

You are set as the handler for this ticket.

outlook test
jjsid345jjsid jjsurlhttps://test.co.uk/support/edit/345jjsurl
```

I have replaced the email addresses but the rest is the same.

I believe the output should be

```
Outlook message reply test
```

But instead it returns the whole message

**Comment by kvannotten** [comment]
Should hopefully be fixed. If you have any other examples that give issues, feel free to reopen this.

**Comment by sazzle2611** [comment]
Thank you for the last fix it worked perfectly and we haven't had any other glitches until now. I wasn't sure whether to open a separate issue for this or not as it's a completely different example.

This example was sent from Thunderbird which uses 2 dashes to separate the message from the signature. The problem only exists if no new line is added at the end of the email.

This returns correctly
```
Hello World

-- 

*Sarah Coxon*
Software Developer
```

With output
```
Hello World
```

But this returns the whole thing
```
Hello World
-- 

*Sarah Coxon*
Software Developer
```

Thanks

**Comment by kvannotten** [comment]
normally thunderbird should effectively add a newline to mail before the signature part. This one is harder to fix because it might have unintentional consequences.
You can put this in a new issue btw, since it's not related. Thanks!

**Comment by sazzle2611** [comment]
Thank you, I have added a new issue
